"""Create the profile-owned Tradefog schema from an empty database.

Revision ID: 0001
Revises: None
Old development schemas are intentionally not migrated.
"""

import sqlalchemy as sa
from alembic import op

from tradefog.db.types import ExactDecimal

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Create the complete initial schema without importing live ORM models."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("first_name", sa.String(length=150), nullable=True),
        sa.Column("last_name", sa.String(length=150), nullable=True),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("username", sa.String(length=150), nullable=False),
        sa.Column("password", sa.String(length=128), nullable=False),
        sa.Column(
            "is_staff",
            sa.Boolean(),
            server_default=sa.false(),
            nullable=False,
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.true(),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "TradingProfile",
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column(
            "venue_type",
            sa.Enum(
                "manual",
                "bybit",
                name="venue_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "is_archived",
            sa.Boolean(),
            server_default=sa.false(),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_TradingProfile_owner_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_TradingProfile")),
    )
    op.create_index(
        "profile_owner_idx", "TradingProfile", ["owner_id", "id"], unique=False
    )
    op.create_table(
        "TradingAsset",
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.true(),
            nullable=False,
        ),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column(
            "asset_type",
            sa.Enum(
                "crypto",
                "equity",
                "fiat",
                name="asset_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.CheckConstraint(
            "symbol = upper(trim(symbol))",
            name=op.f("ck_TradingAsset_normalized_symbol"),
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["TradingProfile.id"],
            name=op.f("fk_TradingAsset_profile_id_TradingProfile"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_TradingAsset")),
    )
    op.create_index(
        "profile_asset_symbol_idx",
        "TradingAsset",
        ["profile_id", "symbol"],
        unique=True,
    )
    op.create_table(
        "TradingStrategy",
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "risk_percent", ExactDecimal(precision=10, scale=6), nullable=False
        ),
        sa.Column(
            "reward_multiple",
            ExactDecimal(precision=10, scale=6),
            server_default="3.000000",
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "at_risk",
                "risk_stopped",
                name="strategy_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "is_archived",
            sa.Boolean(),
            server_default=sa.false(),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.CheckConstraint(
            "CAST(reward_multiple AS NUMERIC) >= 3\n            AND CAST(reward_multiple AS NUMERIC) <= 100\n            AND CAST(reward_multiple AS NUMERIC)\n                = CAST(reward_multiple AS INTEGER)",
            name=op.f("ck_TradingStrategy_strategy_reward_multiple_range"),
        ),
        sa.CheckConstraint(
            "CAST(risk_percent AS NUMERIC) >= 0.01\n            AND CAST(risk_percent AS NUMERIC) <= 100",
            name=op.f("ck_TradingStrategy_strategy_risk_percent_range"),
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["TradingProfile.id"],
            name=op.f("fk_TradingStrategy_profile_id_TradingProfile"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_TradingStrategy")),
    )
    op.create_table(
        "Wallet",
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["TradingProfile.id"],
            name=op.f("fk_Wallet_profile_id_TradingProfile"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_Wallet")),
        sa.UniqueConstraint("profile_id", name=op.f("uq_Wallet_profile_id")),
    )
    op.create_table(
        "TradingInstrument",
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("base_asset_id", sa.Integer(), nullable=False),
        sa.Column("quote_asset_id", sa.Integer(), nullable=False),
        sa.Column("settlement_asset_id", sa.Integer(), nullable=False),
        sa.Column(
            "product",
            sa.Enum(
                "spot",
                "perpetual_future",
                "cash_equity",
                name="product_kind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("exec_symbol", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column(
            "price_step", ExactDecimal(precision=30, scale=18), nullable=False
        ),
        sa.Column(
            "qty_step", ExactDecimal(precision=30, scale=18), nullable=False
        ),
        sa.Column(
            "min_qty", ExactDecimal(precision=30, scale=18), nullable=True
        ),
        sa.Column(
            "min_notional", ExactDecimal(precision=30, scale=18), nullable=True
        ),
        sa.Column("metadata_updated_at", sa.DateTime(), nullable=True),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.true(),
            nullable=False,
        ),
        sa.Column(
            "is_archived",
            sa.Boolean(),
            server_default=sa.false(),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.CheckConstraint(
            "CAST(price_step AS NUMERIC) > 0",
            name=op.f("ck_TradingInstrument_positive_price_step"),
        ),
        sa.CheckConstraint(
            "CAST(qty_step AS NUMERIC) > 0",
            name=op.f("ck_TradingInstrument_positive_qty_step"),
        ),
        sa.CheckConstraint(
            "base_asset_id != quote_asset_id",
            name=op.f("ck_TradingInstrument_distinct_instrument_assets"),
        ),
        sa.ForeignKeyConstraint(
            ["base_asset_id"],
            ["TradingAsset.id"],
            name=op.f("fk_TradingInstrument_base_asset_id_TradingAsset"),
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["TradingProfile.id"],
            name=op.f("fk_TradingInstrument_profile_id_TradingProfile"),
        ),
        sa.ForeignKeyConstraint(
            ["quote_asset_id"],
            ["TradingAsset.id"],
            name=op.f("fk_TradingInstrument_quote_asset_id_TradingAsset"),
        ),
        sa.ForeignKeyConstraint(
            ["settlement_asset_id"],
            ["TradingAsset.id"],
            name=op.f("fk_TradingInstrument_settlement_asset_id_TradingAsset"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_TradingInstrument")),
    )
    op.create_index(
        "profile_instrument_symbol_idx",
        "TradingInstrument",
        ["profile_id", "product", "exec_symbol"],
        unique=True,
    )
    op.create_table(
        "WalletAsset",
        sa.Column("wallet_id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column(
            "risk_stop_capital",
            ExactDecimal(precision=30, scale=18),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "at_risk",
                "risk_stopped",
                name="wallet_asset_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "is_archived",
            sa.Boolean(),
            server_default=sa.false(),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["TradingAsset.id"],
            name=op.f("fk_WalletAsset_asset_id_TradingAsset"),
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["Wallet.id"],
            name=op.f("fk_WalletAsset_wallet_id_Wallet"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_WalletAsset")),
    )
    op.create_index(
        "wallet_asset_asset_idx",
        "WalletAsset",
        ["wallet_id", "asset_id"],
        unique=True,
    )
    op.create_table(
        "StrategyCapital",
        sa.Column("strategy_id", sa.Integer(), nullable=False),
        sa.Column("wallet_asset_id", sa.Integer(), nullable=False),
        sa.Column(
            "capital", ExactDecimal(precision=30, scale=18), nullable=False
        ),
        sa.Column(
            "is_archived",
            sa.Boolean(),
            server_default=sa.false(),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["TradingStrategy.id"],
            name=op.f("fk_StrategyCapital_strategy_id_TradingStrategy"),
        ),
        sa.ForeignKeyConstraint(
            ["wallet_asset_id"],
            ["WalletAsset.id"],
            name=op.f("fk_StrategyCapital_wallet_asset_id_WalletAsset"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_StrategyCapital")),
    )
    op.create_index(
        "strategy_capital_strategy_wallet_asset_idx",
        "StrategyCapital",
        ["strategy_id", "wallet_asset_id"],
        unique=True,
    )
    op.create_table(
        "Trade",
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("strategy_id", sa.Integer(), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "pending_entry",
                "open",
                "closed",
                "cancelled",
                name="trade_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "direction",
            sa.Enum(
                "long",
                "short",
                name="direction",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("description_markdown", sa.Text(), nullable=True),
        sa.Column("quality_rating", sa.Integer(), nullable=True),
        sa.Column("review_completed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "realized_pnl", ExactDecimal(precision=30, scale=18), nullable=True
        ),
        sa.Column(
            "actual_exit_price",
            ExactDecimal(precision=30, scale=18),
            nullable=True,
        ),
        sa.Column(
            "total_commission",
            ExactDecimal(precision=30, scale=18),
            nullable=True,
        ),
        sa.Column(
            "funding_result",
            ExactDecimal(precision=30, scale=18),
            nullable=True,
        ),
        sa.Column("submitted_at", sa.DateTime(), nullable=True),
        sa.Column("opened_at", sa.DateTime(), nullable=True),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.CheckConstraint(
            "quality_rating IS NULL\n            OR (quality_rating >= 1 AND quality_rating <= 10)",
            name=op.f("ck_Trade_trade_quality_rating_range"),
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["TradingInstrument.id"],
            name=op.f("fk_Trade_instrument_id_TradingInstrument"),
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["TradingProfile.id"],
            name=op.f("fk_Trade_profile_id_TradingProfile"),
        ),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["TradingStrategy.id"],
            name=op.f("fk_Trade_strategy_id_TradingStrategy"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_Trade")),
    )
    op.create_index(
        "trade_profile_date_idx",
        "Trade",
        ["profile_id", "trade_date", "id"],
        unique=False,
    )
    op.create_index(
        "trade_profile_rating_idx",
        "Trade",
        ["profile_id", "quality_rating", "id"],
        unique=False,
    )
    op.create_index(
        "trade_profile_review_idx",
        "Trade",
        ["profile_id", "status", "review_completed_at", "id"],
        unique=False,
    )
    op.create_table(
        "WalletOperation",
        sa.Column("wallet_asset_id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "deposit",
                "withdrawal",
                name="wallet_operation_kind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "amount", ExactDecimal(precision=30, scale=18), nullable=False
        ),
        sa.Column("note", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["wallet_asset_id"],
            ["WalletAsset.id"],
            name=op.f("fk_WalletOperation_wallet_asset_id_WalletAsset"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_WalletOperation")),
    )
    op.create_table(
        "Attachment",
        sa.Column("trade_id", sa.Integer(), nullable=False),
        sa.Column("storage_key", sa.String(length=255), nullable=False),
        sa.Column("original_name", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=127), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.CheckConstraint(
            "size_bytes >= 0", name=op.f("ck_Attachment_non_negative_size")
        ),
        sa.ForeignKeyConstraint(
            ["trade_id"],
            ["Trade.id"],
            name=op.f("fk_Attachment_trade_id_Trade"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_Attachment")),
        sa.UniqueConstraint(
            "storage_key", name=op.f("uq_Attachment_storage_key")
        ),
    )
    op.create_table(
        "TradePreparation",
        sa.Column("trade_id", sa.Integer(), nullable=False),
        sa.Column(
            "planned_entry",
            ExactDecimal(precision=30, scale=18),
            nullable=True,
        ),
        sa.Column(
            "planned_stop", ExactDecimal(precision=30, scale=18), nullable=True
        ),
        sa.Column(
            "market_sentiment",
            sa.Enum(
                "NEGATIVE",
                "NEUTRAL",
                "POSITIVE",
                name="market_sentiment",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "information_background",
            sa.Enum(
                "NEGATIVE",
                "NEUTRAL",
                "POSITIVE",
                name="information_background",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "global_daily_direction",
            sa.Enum(
                "NEGATIVE",
                "NEUTRAL",
                "POSITIVE",
                name="global_daily_direction",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "local_daily_movement",
            sa.Enum(
                "NEGATIVE",
                "NEUTRAL",
                "POSITIVE",
                name="local_daily_movement",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "atr_value", ExactDecimal(precision=30, scale=18), nullable=True
        ),
        sa.Column(
            "atr_source",
            sa.Enum(
                "auto",
                "manual",
                name="preparation_atr_source",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("atr_contributing_date", sa.Date(), nullable=True),
        sa.Column("atr_observation_time", sa.DateTime(), nullable=True),
        sa.Column(
            "atr_stale",
            sa.Boolean(),
            server_default=sa.false(),
            nullable=False,
        ),
        sa.Column(
            "observed_session_range",
            ExactDecimal(precision=30, scale=18),
            nullable=True,
        ),
        sa.CheckConstraint(
            "(atr_value IS NULL AND atr_source IS NULL AND atr_contributing_date IS NULL AND atr_observation_time IS NULL AND observed_session_range IS NULL) OR (atr_value IS NOT NULL AND CAST(atr_value AS NUMERIC) > 0 AND atr_source IS NOT NULL AND atr_contributing_date IS NOT NULL AND atr_observation_time IS NOT NULL)",
            name=op.f("ck_TradePreparation_complete_preparation_atr"),
        ),
        sa.CheckConstraint(
            "observed_session_range IS NULL OR CAST(observed_session_range AS NUMERIC) >= 0",
            name=op.f("ck_TradePreparation_nonnegative_session_range"),
        ),
        sa.CheckConstraint(
            "planned_entry IS NULL OR CAST(planned_entry AS NUMERIC) > 0",
            name=op.f("ck_TradePreparation_positive_preparation_entry"),
        ),
        sa.CheckConstraint(
            "planned_stop IS NULL OR CAST(planned_stop AS NUMERIC) > 0",
            name=op.f("ck_TradePreparation_positive_preparation_stop"),
        ),
        sa.ForeignKeyConstraint(
            ["trade_id"],
            ["Trade.id"],
            name=op.f("fk_TradePreparation_trade_id_Trade"),
        ),
        sa.PrimaryKeyConstraint("trade_id", name=op.f("pk_TradePreparation")),
    )
    op.create_table(
        "TradeSnapshot",
        sa.Column("trade_id", sa.Integer(), nullable=False),
        sa.Column("strategy_capital_id", sa.Integer(), nullable=False),
        sa.Column("settlement_asset_id", sa.Integer(), nullable=False),
        sa.Column("instrument_symbol", sa.String(length=64), nullable=False),
        sa.Column(
            "instrument_product",
            sa.Enum(
                "spot",
                "perpetual_future",
                "cash_equity",
                name="snapshot_product_kind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "price_step", ExactDecimal(precision=30, scale=18), nullable=False
        ),
        sa.Column(
            "qty_step", ExactDecimal(precision=30, scale=18), nullable=False
        ),
        sa.Column(
            "min_qty", ExactDecimal(precision=30, scale=18), nullable=True
        ),
        sa.Column(
            "min_notional", ExactDecimal(precision=30, scale=18), nullable=True
        ),
        sa.Column(
            "planned_entry",
            ExactDecimal(precision=30, scale=18),
            nullable=False,
        ),
        sa.Column(
            "planned_stop",
            ExactDecimal(precision=30, scale=18),
            nullable=False,
        ),
        sa.Column(
            "planned_take_profit",
            ExactDecimal(precision=30, scale=18),
            nullable=True,
        ),
        sa.Column(
            "quantity", ExactDecimal(precision=30, scale=18), nullable=True
        ),
        sa.Column(
            "reward_multiple",
            ExactDecimal(precision=10, scale=6),
            nullable=True,
        ),
        sa.Column(
            "planned_risk_percent",
            ExactDecimal(precision=10, scale=6),
            nullable=True,
        ),
        sa.Column(
            "planned_risk_amount",
            ExactDecimal(precision=30, scale=18),
            nullable=True,
        ),
        sa.Column(
            "planned_notional",
            ExactDecimal(precision=30, scale=18),
            nullable=True,
        ),
        sa.Column(
            "allocation_capital",
            ExactDecimal(precision=30, scale=18),
            nullable=True,
        ),
        sa.Column(
            "risk_stop_capital",
            ExactDecimal(precision=30, scale=18),
            nullable=True,
        ),
        sa.Column(
            "already_reserved_risk",
            ExactDecimal(precision=30, scale=18),
            nullable=True,
        ),
        sa.Column(
            "remaining_risk_capacity",
            ExactDecimal(precision=30, scale=18),
            nullable=True,
        ),
        sa.Column("deposit_floor_breach", sa.Boolean(), nullable=True),
        sa.Column(
            "wallet_balance",
            ExactDecimal(precision=30, scale=18),
            nullable=True,
        ),
        sa.Column(
            "wallet_reserved",
            ExactDecimal(precision=30, scale=18),
            nullable=True,
        ),
        sa.Column(
            "wallet_available",
            ExactDecimal(precision=30, scale=18),
            nullable=True,
        ),
        sa.Column(
            "atr_value", ExactDecimal(precision=30, scale=18), nullable=True
        ),
        sa.Column(
            "atr_source",
            sa.Enum(
                "auto",
                "manual",
                name="atr_source",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("atr_contributing_date", sa.Date(), nullable=True),
        sa.Column("atr_observation_time", sa.DateTime(), nullable=True),
        sa.Column("atr_stale", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["settlement_asset_id"],
            ["TradingAsset.id"],
            name=op.f("fk_TradeSnapshot_settlement_asset_id_TradingAsset"),
        ),
        sa.ForeignKeyConstraint(
            ["strategy_capital_id"],
            ["StrategyCapital.id"],
            name=op.f("fk_TradeSnapshot_strategy_capital_id_StrategyCapital"),
        ),
        sa.ForeignKeyConstraint(
            ["trade_id"],
            ["Trade.id"],
            name=op.f("fk_TradeSnapshot_trade_id_Trade"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_TradeSnapshot")),
        sa.UniqueConstraint(
            "trade_id", name=op.f("uq_TradeSnapshot_trade_id")
        ),
    )
    op.create_table(
        "TradeReservation",
        sa.Column("trade_snapshot_id", sa.Integer(), nullable=False),
        sa.Column("wallet_asset_id", sa.Integer(), nullable=False),
        sa.Column(
            "purpose",
            sa.Enum(
                "position_funding",
                "inventory",
                "loss_buffer",
                name="reservation_purpose",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "amount", ExactDecimal(precision=30, scale=18), nullable=False
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.CheckConstraint(
            "CAST(amount AS NUMERIC) > 0",
            name=op.f("ck_TradeReservation_positive_reservation"),
        ),
        sa.ForeignKeyConstraint(
            ["trade_snapshot_id"],
            ["TradeSnapshot.id"],
            name=op.f("fk_TradeReservation_trade_snapshot_id_TradeSnapshot"),
        ),
        sa.ForeignKeyConstraint(
            ["wallet_asset_id"],
            ["WalletAsset.id"],
            name=op.f("fk_TradeReservation_wallet_asset_id_WalletAsset"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_TradeReservation")),
    )
    op.create_index(
        "reservation_snapshot_purpose_idx",
        "TradeReservation",
        ["trade_snapshot_id", "purpose"],
        unique=True,
    )
    op.create_index(
        "reservation_wallet_snapshot_idx",
        "TradeReservation",
        ["wallet_asset_id", "trade_snapshot_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop this baseline's tables in reverse dependency order."""
    op.drop_table("TradeReservation")
    op.drop_table("TradeSnapshot")
    op.drop_table("TradePreparation")
    op.drop_table("Attachment")
    op.drop_table("WalletOperation")
    op.drop_table("Trade")
    op.drop_table("StrategyCapital")
    op.drop_table("WalletAsset")
    op.drop_table("TradingInstrument")
    op.drop_table("Wallet")
    op.drop_table("TradingStrategy")
    op.drop_table("TradingAsset")
    op.drop_table("TradingProfile")
    op.drop_table("users")
