"""URL configuration for the tradefog journal application."""

from django.urls import path

from tradefog.journal import views

app_name = "journal"

urlpatterns = [
    path("", views.home, name="home"),
    # Profiles:
    path(
        "profiles/",
        views.profile_overview,
        name="profile_overview",
    ),
    path(
        "profiles/create/",
        views.profile_create,
        name="profile_create",
    ),
    path(
        "profiles/<int:pk>/archive/",
        views.profile_archive,
        name="profile_archive",
    ),
    path(
        "profiles/<int:pk>/restore/",
        views.profile_restore,
        name="profile_restore",
    ),
    path(
        "profiles/<int:pk>/delete/",
        views.profile_delete,
        name="profile_delete",
    ),
    path(
        "profiles/<int:pk>/",
        views.profile_detail,
        name="profile_detail",
    ),
    path(
        "profiles/<int:pk>/edit/",
        views.profile_edit,
        name="profile_edit",
    ),
    path(
        "profiles/<int:pk>/wallet/assets/add/",
        views.wallet_add,
        name="wallet_add",
    ),
    path(
        "profiles/<int:pk>/wallet/assets/<int:asset_pk>/deposit/",
        views.wallet_deposit,
        name="wallet_deposit",
    ),
    path(
        "profiles/<int:pk>/wallet/assets/<int:asset_pk>/withdraw/",
        views.wallet_withdraw,
        name="wallet_withdraw",
    ),
    path(
        "profiles/<int:pk>/wallet/assets/<int:asset_pk>/edit/",
        views.wallet_edit,
        name="wallet_edit",
    ),
    path(
        "profiles/<int:pk>/wallet/assets/<int:asset_pk>/remove/",
        views.wallet_remove,
        name="wallet_remove",
    ),
    path(
        "profiles/<int:pk>/wallet/assets/<int:asset_pk>/restore/",
        views.wallet_restore,
        name="wallet_restore",
    ),
    path(
        "profiles/<int:pk>/wallet/operations/<int:operation_pk>/edit/",
        views.wallet_operation_edit,
        name="wallet_operation_edit",
    ),
    path(
        "profiles/<int:pk>/strategies/create/",
        views.strategy_create,
        name="strategy_create",
    ),
    path(
        "profiles/<int:pk>/strategies/<int:strategy_pk>/edit/",
        views.strategy_edit,
        name="strategy_edit",
    ),
    path(
        "profiles/<int:pk>/strategies/<int:strategy_pk>/detail/",
        views.strategy_detail,
        name="strategy_detail",
    ),
    path(
        "profiles/<int:pk>/strategies/<int:strategy_pk>/archive/",
        views.strategy_archive,
        name="strategy_archive",
    ),
    path(
        "profiles/<int:pk>/strategies/<int:strategy_pk>/restore/",
        views.strategy_restore,
        name="strategy_restore",
    ),
    path(
        "profiles/<int:pk>/strategies/<int:strategy_pk>/capital/add/",
        views.strategy_capital_add,
        name="strategy_capital_add",
    ),
    path(
        "profiles/<int:pk>/strategies/<int:strategy_pk>/capital/"
        + "<int:capital_pk>/archive/",
        views.strategy_capital_archive,
        name="strategy_capital_archive",
    ),
    path(
        "profiles/<int:pk>/strategies/<int:strategy_pk>/capital/"
        + "<int:capital_pk>/restore/",
        views.strategy_capital_restore,
        name="strategy_capital_restore",
    ),
    # Trades:
    path("trades/", views.trade_overview, name="trades"),
    path("trades/new/", views.trade_create, name="trade_create"),
    path("trades/<int:pk>/", views.trade_workspace, name="trade_workspace"),
    path("trades/<int:pk>/submit/", views.trade_submit, name="trade_submit"),
    path("trades/<int:pk>/open/", views.trade_open_action, name="trade_open"),
    path(
        "trades/<int:pk>/close/",
        views.trade_close_action,
        name="trade_close",
    ),
    path(
        "trades/<int:pk>/cancel/",
        views.trade_cancel_action,
        name="trade_cancel",
    ),
    path(
        "trades/<int:pk>/delete/",
        views.trade_delete,
        name="trade_delete",
    ),
    path(
        "trades/<int:pk>/description/",
        views.trade_description_update,
        name="trade_description_update",
    ),
    path(
        "trades/<int:pk>/review-status/",
        views.trade_review_toggle,
        name="trade_review_toggle",
    ),
    path(
        "trades/<int:pk>/attachments/",
        views.trade_attachment_upload,
        name="trade_attachment_upload",
    ),
    path(
        "trades/<int:pk>/attachments/<int:attachment_pk>/",
        views.trade_attachment_serve,
        name="trade_attachment_serve",
    ),
    path(
        "trades/<int:pk>/attachments/<int:attachment_pk>/delete/",
        views.trade_attachment_delete,
        name="trade_attachment_delete",
    ),
    path("trades/options/", views.trade_workspace_options, name="trade_options"),
    path(
        "trades/workspace/options/",
        views.trade_workspace_options,
        name="trade_workspace_options",
    ),
    path(
        "trades/workspace/market-data/",
        views.trade_market_data,
        name="trade_market_data",
    ),

    path("analytics/", views.analytics, name="analytics"),
    # Catalog:
    path(
        "catalog/assets/",
        views.asset_overview,
        name="asset_overview",
    ),
    path(
        "catalog/assets/create/",
        views.asset_create,
        name="asset_create",
    ),
    path(
        "catalog/assets/<int:pk>/delete/",
        views.asset_delete,
        name="asset_delete",
    ),
    path(
        "catalog/pairs/",
        views.pair_overview,
        name="pair_overview",
    ),
    path(
        "catalog/pairs/create/",
        views.pair_create,
        name="pair_create",
    ),
    path(
        "catalog/pairs/<int:pk>/delete/",
        views.pair_delete,
        name="pair_delete",
    ),
    path(
        "catalog/venues/",
        views.venue_overview,
        name="venue_overview",
    ),
    path(
        "catalog/venues/create/",
        views.venue_create,
        name="venue_create",
    ),
    path(
        "catalog/venues/<int:pk>/",
        views.venue_detail,
        name="venue_detail",
    ),
    path(
        "catalog/venues/<int:pk>/edit/",
        views.venue_edit,
        name="venue_edit",
    ),
    path(
        "catalog/venues/<int:pk>/archive/",
        views.venue_archive,
        name="venue_archive",
    ),
    path(
        "catalog/venues/<int:pk>/delete/",
        views.venue_delete,
        name="venue_delete",
    ),
    path(
        "catalog/venues/<int:pk>/restore/",
        views.venue_restore,
        name="venue_restore",
    ),
    path(
        "catalog/venues/<int:pk>/wallet-assets/add/",
        views.wallet_asset_add,
        name="wallet_asset_add",
    ),
    path(
        "catalog/venues/<int:pk>/wallet-assets/<int:asset_pk>/edit/",
        views.wallet_asset_edit,
        name="wallet_asset_edit",
    ),
    path(
        "catalog/venues/<int:pk>/wallet-assets/<int:asset_pk>/remove/",
        views.wallet_asset_remove,
        name="wallet_asset_remove",
    ),
    path(
        "catalog/venues/<int:pk>/instruments/add/",
        views.instrument_add,
        name="instrument_add",
    ),
    path(
        "catalog/venues/<int:pk>/instruments/<int:instrument_pk>/edit/",
        views.instrument_edit,
        name="instrument_edit",
    ),
    path(
        "catalog/venues/<int:pk>/instruments/<int:instrument_pk>/detail/",
        views.instrument_detail,
        name="instrument_detail",
    ),
    path(
        "catalog/venues/<int:pk>/instruments/<int:instrument_pk>/delete/",
        views.instrument_delete,
        name="instrument_delete",
    ),
]
