# Generated by Django 5.2.17 on 2026-08-29 06:43
# ruff: noqa: FURB157, RUF012
# pyright: reportAny=false, reportUnannotatedClassAttribute=false

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TradingProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Name"),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("MANUAL", "Manual")],
                        default="MANUAL",
                        editable=False,
                        max_length=20,
                        verbose_name="Execution provider",
                    ),
                ),
                (
                    "capital_currency",
                    models.CharField(
                        help_text="Currency used for capital, risk, and realized P&L.",
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use letters, numbers, dots, underscores, or hyphens.",
                                regex="^[A-Za-z0-9][A-Za-z0-9._-]*$",
                            )
                        ],
                        verbose_name="Capital currency",
                    ),
                ),
                (
                    "initial_capital",
                    models.DecimalField(
                        decimal_places=8,
                        max_digits=24,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("1E-12")
                            )
                        ],
                        verbose_name="Initial trading capital",
                    ),
                ),
                (
                    "risk_per_trade_percent",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("1.000"),
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.001")
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal("100")
                            ),
                        ],
                        verbose_name="Risk per trade, %",
                    ),
                ),
                (
                    "risk_stop_capital",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Trading should stop when current capital reaches this absolute amount.",
                        max_digits=24,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0")
                            )
                        ],
                        verbose_name="Risk stop capital",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("AT_RISK", "At risk"),
                            ("RISK_STOPPED", "Risk stopped"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="ACTIVE",
                        editable=False,
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, editable=False, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trading_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="CapitalOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("DEPOSIT", "Deposit"),
                            ("WITHDRAWAL", "Withdrawal"),
                        ],
                        max_length=20,
                        verbose_name="Operation",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=8,
                        max_digits=24,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("1E-12")
                            )
                        ],
                        verbose_name="Amount",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Note"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capital_operations",
                        to="journal.tradingprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ProfileInstrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_asset",
                    models.CharField(
                        help_text="The traded asset; profile capital is the quote asset.",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use letters, numbers, dots, underscores, or hyphens.",
                                regex="^[A-Za-z0-9][A-Za-z0-9._-]*$",
                            )
                        ],
                        verbose_name="Base asset",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Display name"
                    ),
                ),
                (
                    "market_type",
                    models.CharField(
                        choices=[("SPOT", "Spot"), ("LINEAR", "Linear")],
                        default="SPOT",
                        max_length=10,
                        verbose_name="Market type",
                    ),
                ),
                (
                    "price_step",
                    models.DecimalField(
                        decimal_places=12,
                        max_digits=24,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("1E-12")
                            )
                        ],
                        verbose_name="Price step",
                    ),
                ),
                (
                    "quantity_step",
                    models.DecimalField(
                        decimal_places=12,
                        max_digits=24,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("1E-12")
                            )
                        ],
                        verbose_name="Quantity step",
                    ),
                ),
                (
                    "minimum_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=12,
                        max_digits=24,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("1E-12")
                            )
                        ],
                        verbose_name="Minimum quantity",
                    ),
                ),
                (
                    "minimum_notional",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="Minimum order value in the profile capital currency.",
                        max_digits=24,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("1E-12")
                            )
                        ],
                        verbose_name="Minimum notional",
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, editable=False, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instruments",
                        to="journal.tradingprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["base_asset", "market_type", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("archived_at__isnull", True)),
                        fields=("profile", "base_asset", "market_type"),
                        name="unique_active_profile_instrument_market",
                        violation_error_message="An active instrument already uses this market.",
                    )
                ],
            },
        ),
    ]
