# Generated by Django 5.2.17 on 2026-08-28 11:10
# ruff: noqa: FURB157, RUF012
# pyright: reportAny=false, reportUnannotatedClassAttribute=false

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TradingProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Name"),
                ),
                (
                    "venue_name",
                    models.CharField(max_length=100, verbose_name="Venue"),
                ),
                (
                    "capital_currency",
                    models.CharField(
                        help_text="Currency used for capital, risk, and realized P&L.",
                        max_length=12,
                        verbose_name="Capital currency",
                    ),
                ),
                (
                    "initial_capital",
                    models.DecimalField(
                        decimal_places=8,
                        max_digits=24,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("1E-12")
                            )
                        ],
                        verbose_name="Initial trading capital",
                    ),
                ),
                (
                    "risk_per_trade_percent",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.330"),
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.001")
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal("100")
                            ),
                        ],
                        verbose_name="Risk per trade, %",
                    ),
                ),
                (
                    "reward_multiple",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("3.00"),
                        help_text="Target profit expressed as a multiple of trade risk.",
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.01")
                            )
                        ],
                        verbose_name="Reward multiple",
                    ),
                ),
                (
                    "daily_risk_limit_percent",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("1.000"),
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.001")
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal("100")
                            ),
                        ],
                        verbose_name="Daily risk limit, %",
                    ),
                ),
                (
                    "monthly_target_percent",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("3.000"),
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.001")
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal("100")
                            ),
                        ],
                        verbose_name="Monthly target, %",
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, editable=False, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trading_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProfileInstrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        help_text="Venue symbol, for example BTC/USDT or AAPL.",
                        max_length=40,
                        verbose_name="Symbol",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Display name"
                    ),
                ),
                (
                    "market_type",
                    models.CharField(
                        choices=[("SPOT", "Spot"), ("LINEAR", "Linear")],
                        default="SPOT",
                        max_length=10,
                        verbose_name="Market type",
                    ),
                ),
                (
                    "price_step",
                    models.DecimalField(
                        decimal_places=12,
                        max_digits=24,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("1E-12")
                            )
                        ],
                        verbose_name="Price step",
                    ),
                ),
                (
                    "quantity_step",
                    models.DecimalField(
                        decimal_places=12,
                        max_digits=24,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("1E-12")
                            )
                        ],
                        verbose_name="Quantity step",
                    ),
                ),
                (
                    "minimum_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=12,
                        max_digits=24,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("1E-12")
                            )
                        ],
                        verbose_name="Minimum quantity",
                    ),
                ),
                (
                    "minimum_notional",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="Minimum order value in the profile capital currency.",
                        max_digits=24,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("1E-12")
                            )
                        ],
                        verbose_name="Minimum notional",
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, editable=False, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instruments",
                        to="journal.tradingprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["symbol", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("archived_at__isnull", True)),
                        fields=("profile", "symbol"),
                        name="unique_active_profile_instrument_symbol",
                        violation_error_message="An active instrument with this symbol already exists.",
                    )
                ],
            },
        ),
    ]
