# Generated by Django 5.2.17 on 2026-08-30 00:49
# ruff: noqa: FURB157, RUF012
# pyright: reportAny=false, reportUnannotatedClassAttribute=false

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        help_text="Canonical symbol used inside Tradefog, for example BTC.",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use letters, numbers, dots, underscores, or hyphens.",
                                regex="^[A-Za-z0-9][A-Za-z0-9._-]*$",
                            )
                        ],
                        verbose_name="Symbol",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=100, verbose_name="Name"),
                ),
                (
                    "asset_class",
                    models.CharField(
                        choices=[
                            ("CRYPTO", "Cryptocurrency"),
                            ("EQUITY", "Equity"),
                            ("FIAT", "Fiat currency"),
                            ("OTHER", "Other"),
                        ],
                        default="CRYPTO",
                        max_length=20,
                        verbose_name="Asset class",
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["symbol", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProfileTradingPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_step",
                    models.DecimalField(
                        decimal_places=12,
                        max_digits=24,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1E-12"))
                        ],
                        verbose_name="Price step",
                    ),
                ),
                (
                    "quantity_step",
                    models.DecimalField(
                        decimal_places=12,
                        max_digits=24,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1E-12"))
                        ],
                        verbose_name="Quantity step",
                    ),
                ),
                (
                    "minimum_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=12,
                        max_digits=24,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1E-12"))
                        ],
                        verbose_name="Minimum quantity",
                    ),
                ),
                (
                    "minimum_notional",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="Minimum order value in the profile capital currency.",
                        max_digits=24,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1E-12"))
                        ],
                        verbose_name="Minimum notional",
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        help_text="Asset traded against the profile capital asset.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trading_pairs",
                        to="journal.asset",
                        verbose_name="Base asset",
                    ),
                ),
            ],
            options={
                "ordering": ["asset__symbol", "id"],
            },
        ),
        migrations.CreateModel(
            name="TradingProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "provider",
                    models.CharField(
                        choices=[("MANUAL", "Manual")],
                        default="MANUAL",
                        editable=False,
                        max_length=20,
                        verbose_name="Execution provider",
                    ),
                ),
                (
                    "market_type",
                    models.CharField(
                        choices=[
                            ("SPOT", "Spot"),
                            ("LINEAR_PERPETUAL", "Linear perpetual"),
                        ],
                        default="SPOT",
                        help_text="Spot supports LONG only; linear perpetual supports LONG and SHORT at 1x.",
                        max_length=24,
                        verbose_name="Market type",
                    ),
                ),
                (
                    "initial_capital",
                    models.DecimalField(
                        decimal_places=8,
                        max_digits=24,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1E-12"))
                        ],
                        verbose_name="Initial trading capital",
                    ),
                ),
                (
                    "risk_per_trade_percent",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("1.000"),
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Risk per trade, %",
                    ),
                ),
                (
                    "risk_stop_capital",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Trading should stop when current capital reaches this absolute amount.",
                        max_digits=24,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Risk stop capital",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("AT_RISK", "At risk"),
                            ("RISK_STOPPED", "Risk stopped"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="ACTIVE",
                        editable=False,
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "capital_asset",
                    models.ForeignKey(
                        help_text="Quote asset used for capital, risk, and realized P&L.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capital_profiles",
                        to="journal.asset",
                        verbose_name="Capital asset",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trading_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_ENTRY", "Pending entry"),
                            ("OPEN", "Open"),
                            ("CLOSED", "Closed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        editable=False,
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("LONG", "LONG"), ("SHORT", "SHORT")],
                        max_length=10,
                        verbose_name="Direction",
                    ),
                ),
                ("trade_date", models.DateField(verbose_name="Trade date")),
                (
                    "planned_entry",
                    models.DecimalField(
                        decimal_places=12,
                        max_digits=24,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1E-12"))
                        ],
                        verbose_name="Planned entry",
                    ),
                ),
                (
                    "planned_stop",
                    models.DecimalField(
                        decimal_places=12,
                        max_digits=24,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1E-12"))
                        ],
                        verbose_name="Planned stop",
                    ),
                ),
                (
                    "planned_take_profit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=12,
                        editable=False,
                        max_digits=24,
                        null=True,
                        verbose_name="Planned take profit",
                    ),
                ),
                (
                    "planned_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=12,
                        editable=False,
                        max_digits=24,
                        null=True,
                        verbose_name="Planned quantity",
                    ),
                ),
                (
                    "planned_risk_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        editable=False,
                        max_digits=6,
                        null=True,
                        verbose_name="Planned risk percent",
                    ),
                ),
                (
                    "planned_risk_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=24,
                        editable=False,
                        max_digits=48,
                        null=True,
                        verbose_name="Planned risk amount",
                    ),
                ),
                (
                    "reward_multiple",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        editable=False,
                        max_digits=6,
                        null=True,
                        verbose_name="Reward multiple",
                    ),
                ),
                (
                    "capital_snapshot",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        editable=False,
                        max_digits=24,
                        null=True,
                        verbose_name="Capital snapshot",
                    ),
                ),
                (
                    "risk_base_snapshot",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        editable=False,
                        max_digits=24,
                        null=True,
                        verbose_name="Risk base snapshot",
                    ),
                ),
                (
                    "risk_stop_snapshot",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        editable=False,
                        max_digits=24,
                        null=True,
                        verbose_name="Risk stop snapshot",
                    ),
                ),
                (
                    "reserved_risk_snapshot",
                    models.DecimalField(
                        blank=True,
                        decimal_places=24,
                        editable=False,
                        max_digits=48,
                        null=True,
                        verbose_name="Reserved risk snapshot",
                    ),
                ),
                (
                    "risk_capacity_snapshot",
                    models.DecimalField(
                        blank=True,
                        decimal_places=24,
                        editable=False,
                        max_digits=48,
                        null=True,
                        verbose_name="Risk capacity snapshot",
                    ),
                ),
                (
                    "risk_limit_breached",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        verbose_name="Risk limit breached",
                    ),
                ),
                (
                    "notional_limit_breached",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        verbose_name="Notional limit breached",
                    ),
                ),
                (
                    "realized_pnl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=24,
                        null=True,
                        verbose_name="Realized P&L",
                    ),
                ),
                (
                    "result_r",
                    models.DecimalField(
                        blank=True,
                        decimal_places=24,
                        editable=False,
                        max_digits=48,
                        null=True,
                        verbose_name="Result in R",
                    ),
                ),
                (
                    "actual_exit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=12,
                        max_digits=24,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1E-12"))
                        ],
                        verbose_name="Actual exit price",
                    ),
                ),
                (
                    "commission_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="Optional reference total already included in P&L.",
                        max_digits=24,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Commission",
                    ),
                ),
                (
                    "funding_result",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="Optional signed funding already included in P&L: negative when paid and positive when received.",
                        max_digits=24,
                        null=True,
                        verbose_name="Funding result",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "submitted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "filled_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "closed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "trading_pair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trades",
                        to="journal.profiletradingpair",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trades",
                        to="journal.tradingprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-trade_date", "-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="profiletradingpair",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trading_pairs",
                to="journal.tradingprofile",
            ),
        ),
        migrations.CreateModel(
            name="CapitalOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[("DEPOSIT", "Deposit"), ("WITHDRAWAL", "Withdrawal")],
                        max_length=20,
                        verbose_name="Operation",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=8,
                        max_digits=24,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1E-12"))
                        ],
                        verbose_name="Amount",
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=200, verbose_name="Note"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capital_operations",
                        to="journal.tradingprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("symbol"),
                models.F("owner"),
                name="unique_owner_asset_symbol",
            ),
        ),
        migrations.AddConstraint(
            model_name="profiletradingpair",
            constraint=models.UniqueConstraint(
                condition=models.Q(("archived_at__isnull", True)),
                fields=("profile", "asset"),
                name="unique_active_profile_trading_pair",
                violation_error_message="An active trading pair already uses this asset.",
            ),
        ),
    ]
