# Generated by Django 5.2.17 on 2026-09-06 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TradeAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="trade_attachments/%Y/%m/%d/",
                        verbose_name="File",
                    ),
                ),
                (
                    "original_name",
                    models.CharField(
                        max_length=255, verbose_name="Original name"
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        max_length=128, verbose_name="Content type"
                    ),
                ),
                (
                    "size",
                    models.PositiveIntegerField(verbose_name="Size in bytes"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created at"
                    ),
                ),
                (
                    "trade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="journal.trade",
                        verbose_name="Trade",
                    ),
                ),
            ],
            options={
                "verbose_name": "trade attachment",
                "verbose_name_plural": "trade attachments",
                "ordering": ("created_at",),
            },
        ),
    ]
