# Generated by Django 5.2.17 on 2026-09-04 12:42
# pyright: reportUnannotatedClassAttribute=false

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="tradingprofile",
            constraint=models.UniqueConstraint(
                fields=("owner", "name"), name="trading_profile_owner_name_idx"
            ),
        ),
    ]
