# Generated by Django 5.2.17 on 2026-08-30 05:21
# ruff: noqa: RUF012
# pyright: reportAny=false, reportUnannotatedClassAttribute=false

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TradeChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schema_version",
                    models.PositiveSmallIntegerField(default=1, editable=False),
                ),
                (
                    "market_sentiment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NEGATIVE", "Negative"),
                            ("NEUTRAL", "Neutral"),
                            ("POSITIVE", "Positive"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Broad market sentiment",
                    ),
                ),
                (
                    "information_background",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NEGATIVE", "Negative"),
                            ("NEUTRAL", "Neutral"),
                            ("POSITIVE", "Positive"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Information background",
                    ),
                ),
                (
                    "global_daily_direction",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NEGATIVE", "Negative"),
                            ("NEUTRAL", "Neutral"),
                            ("POSITIVE", "Positive"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Global D1 direction",
                    ),
                ),
                (
                    "local_daily_movement",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NEGATIVE", "Negative"),
                            ("NEUTRAL", "Neutral"),
                            ("POSITIVE", "Positive"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Local D1 movement",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trade",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist",
                        to="journal.trade",
                    ),
                ),
            ],
        ),
    ]
