# Generated by Django 5.2.17 on 2026-09-05 07:42
# pyright: reportUnannotatedClassAttribute=false
# pyright: reportUnknownArgumentType=false

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0002_tradingprofile_trading_profile_owner_name_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategycapital",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("archived", "Archived")],
                default="active",
                max_length=32,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="tradingstrategy",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("at_risk", "At risk"),
                    ("risk_stopped", "Below floor"),
                    ("archived", "Archived"),
                ],
                default="active",
                max_length=32,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="walletasset",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("at_risk", "At risk"),
                    ("risk_stopped", "Below floor"),
                ],
                default="active",
                max_length=32,
                verbose_name="Status",
            ),
        ),
    ]
