# Generated by Django 5.2.17 on 2026-08-30 10:06
# ruff: noqa: RUF012
# pyright: reportAny=false, reportUnannotatedClassAttribute=false

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0002_tradechecklist"),
    ]

    operations = [
        migrations.AddField(
            model_name="profiletradingpair",
            name="market_data_provider",
            field=models.CharField(
                choices=[("MANUAL", "Manual"), ("BYBIT", "Bybit")],
                default="MANUAL",
                help_text="Tradefog always calculates ATR from the stored daily candles.",
                max_length=10,
                verbose_name="Market data source",
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="atr_as_of_date_snapshot",
            field=models.DateField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="ATR through date",
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="atr_source_snapshot",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=20,
                verbose_name="ATR source",
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="atr_value_snapshot",
            field=models.DecimalField(
                blank=True,
                decimal_places=12,
                editable=False,
                max_digits=24,
                null=True,
                verbose_name="ATR snapshot",
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="market_data_stale_snapshot",
            field=models.BooleanField(
                default=False,
                editable=False,
                verbose_name="Market data was stale",
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="session_observed_at_snapshot",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="Session observed at",
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="session_range_percent_snapshot",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                editable=False,
                max_digits=12,
                null=True,
                verbose_name="Observed range as ATR percent",
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="session_range_snapshot",
            field=models.DecimalField(
                blank=True,
                decimal_places=12,
                editable=False,
                max_digits=24,
                null=True,
                verbose_name="Observed session range",
            ),
        ),
        migrations.CreateModel(
            name="MarketDataState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_session_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "current_high",
                    models.DecimalField(
                        blank=True, decimal_places=12, max_digits=24, null=True
                    ),
                ),
                (
                    "current_low",
                    models.DecimalField(
                        blank=True, decimal_places=12, max_digits=24, null=True
                    ),
                ),
                (
                    "current_observed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "last_attempt_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "last_success_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("last_error", models.CharField(blank=True, max_length=300)),
                (
                    "trading_pair",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_data_state",
                        to="journal.profiletradingpair",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyCandle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trading_date",
                    models.DateField(
                        help_text="Bybit daily candles use UTC session dates.",
                        verbose_name="Trading date",
                    ),
                ),
                (
                    "open_price",
                    models.DecimalField(
                        decimal_places=12,
                        max_digits=24,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("1E-12")
                            )
                        ],
                        verbose_name="Open price",
                    ),
                ),
                (
                    "high_price",
                    models.DecimalField(
                        decimal_places=12,
                        max_digits=24,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("1E-12")
                            )
                        ],
                        verbose_name="High price",
                    ),
                ),
                (
                    "low_price",
                    models.DecimalField(
                        decimal_places=12,
                        max_digits=24,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("1E-12")
                            )
                        ],
                        verbose_name="Low price",
                    ),
                ),
                (
                    "close_price",
                    models.DecimalField(
                        decimal_places=12,
                        max_digits=24,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("1E-12")
                            )
                        ],
                        verbose_name="Close price",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("MANUAL", "Manual"), ("BYBIT", "Bybit")],
                        default="MANUAL",
                        editable=False,
                        max_length=10,
                        verbose_name="Source",
                    ),
                ),
                (
                    "fetched_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trading_pair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_candles",
                        to="journal.profiletradingpair",
                    ),
                ),
            ],
            options={
                "ordering": ["-trading_date", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("trading_pair", "trading_date"),
                        name="unique_pair_daily_candle",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("high_price__gte", models.F("low_price"))
                        ),
                        name="daily_candle_high_gte_low",
                    ),
                ],
            },
        ),
    ]
