# Generated by Django 5.2.17 on 2026-09-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0002_tradeattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="draft_context",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Draft context"
            ),
        ),
    ]
