# Generated by Django 5.2.17 on 2026-08-30 17:41
# ruff: noqa: RUF012
# pyright: reportAny=false, reportUnannotatedClassAttribute=false

import django.db.models.deletion
from django.db import migrations, models

import tradefog.journal.models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0003_market_data_and_atr"),
    ]

    operations = [
        migrations.CreateModel(
            name="TradeAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=500,
                        upload_to=tradefog.journal.models.trade_attachment_path,
                        verbose_name="File",
                    ),
                ),
                (
                    "original_name",
                    models.CharField(
                        max_length=255, verbose_name="Original filename"
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        max_length=100, verbose_name="Content type"
                    ),
                ),
                ("size", models.PositiveBigIntegerField(verbose_name="Size")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="journal.trade",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="TradeDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_markdown",
                    models.TextField(
                        blank=True, verbose_name="Trade description"
                    ),
                ),
                (
                    "review_completed_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Review completed at",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trade",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="description",
                        to="journal.trade",
                    ),
                ),
            ],
        ),
    ]
